services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:Ho2025@host.docker.internal:5432/mental_health_app
      - JWT_SECRET=your-secret-key-change-in-production
      - OPENAI_API_KEY=your-openai-api-key
      - PORT=3000 