services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-mental_health_app}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-passw}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-mental_health_app}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      # Database configuration
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-passw}@postgres:5432/${DB_NAME:-mental_health_app}
      
      # Application configuration
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      - PORT=${PORT:-3000}
      - NODE_ENV=${NODE_ENV:-production}
      
      # AI Services configuration
      - OLLAMA_API_URL=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-qwen2.5:0.5b}
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started
      ollama-init:
        condition: service_completed_successfully
    networks:
      - app-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    networks:
      - app-network

  # Servicio para inicializar Ollama con el modelo
  ollama-init:
    image: curlimages/curl:latest
    depends_on:
      - ollama
    volumes:
      - ./scripts/init-ollama.sh:/init-ollama.sh:ro
    command: ["sh", "/init-ollama.sh"]
    networks:
      - app-network
    restart: "no"

volumes:
  postgres_data:
    driver: local
  ollama_data:
    driver: local

networks:
  app-network:
    driver: bridge 